name: 'WIP/Move all cards on projects'
description: 'To specific column from specific column'
author: 'HiromiShikata'
inputs:
  milliseconds:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
